language: python
python:
  - "3.5"

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install tox
  - virtualenv --version
  - pip --version
  - tox --version

# command to run tests
script: tox

#after_success:
#  - coveralls
